[tool.poetry]
name = "captura-downloads"
version = "0.1.0"
description = ""
authors = ["Rodrigo Prado de Jesus <royopa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
blue = "^0.9.1"
isort = "^6.0.0"
taskipy = "^1.14.1"


[tool.poetry.group.doc.dependencies]
mkdocs-material = "^9.6.3"
mkdocstrings = "^0.28.0"
mkdocstrings-python = "^1.14.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
